ARG REPO_URL

# STAGE 1: Start from the latest image and sync portage
FROM ${REPO_URL}:latest AS setup
RUN emaint sync -a>/dev/null

# STAGE 2: Emerge LLVM
FROM setup AS llvm
RUN emerge --update -v llvm-core/llvm

# STAGE 3: Emerge Clang
FROM llvm AS clang
RUN emerge --update -v llvm-core/clang

# STAGE 4: Emerge @world
FROM clang AS world
RUN emerge --update --deep --newuse -v @world

# STAGE 5: Final image
FROM world AS final
RUN emerge --onlydeps -v www-client/google-chrome-unstable
