# SPDX-FileCopyrightText: Copyright 2025 Florian Albrechtskirchinger <falbrechtskirchinger@gmail.com>
#
# SPDX-License-Identifier: MIT

name: ⚙️ Update ebuilds

on:
  # Run every 3 hours
  schedule:
    - cron: '30 */3 * * *'
  workflow_dispatch:

jobs:
  update-ebuilds:
    name: Update ebuilds
    runs-on: ubuntu-latest
    outputs:
      new_ebuilds: ${{ steps.update-ebuilds.outputs.new_ebuilds }}
    permissions:
      # Required to push changes to repo
      contents: write

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Set git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update ebuilds
        id: update-ebuilds
        run: |
          python scripts/update_ebuilds.py -v --update --commit --step-summary
          git push

      - name: Store HEAD commit hash
        run: git rev-parse HEAD > commit_hash.txt

      - name: Upload commit hash
        uses: actions/upload-artifact@v4
        with:
          name: commit_hash
          path: commit_hash.txt
          retention-days: 1
